### ISSUE TITLE
obtain the list of files of one PR

### ISSUE THREAD

**Issue by dgutson** [GonzaloGarciaZurlo/CodeDesignDeltaEvaluator#2]
The goal of this issue is to obtain the list of files to analyze. These files belong to the tag of a given PR, before and after.

Processing:

1. git to temp dir `before` of files before the PR (that is, where it wants to merge to).
2. git to temp dir `after` of the PR the files changed belong to
3. analyze files (of before and after in temp dirs)
4. remove temp dirs

This can be implemented as a bash script.

Use mktemp to ensure there will not be concurrent issues.

**Comment by GonzaloGarciaZurlo** [comment]
- [ ] New examples format (considering multiple files)

- [ ]  Modify the use of UML generators to receive multiple files

- [ ] Add support for java

- [ ] Get files from PR (Before and After)
