### ISSUE TITLE
finish MVP metrics

### ISSUE THREAD

**Issue by dgutson** [GonzaloGarciaZurlo/CodeDesignDeltaEvaluator#3]
- [x] number of classes that changed their base classes
- [x] expression-based metrics
- [x] afferent/efferent metrics
- [x] Abstractness (in total of classes)
- [x] Instability (per class)

**Comment by GonzaloGarciaZurlo** [comment]
I also add to this issue:

- [ ]  the refactoring of the addons/queries_cypher file
